version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi-hole
    network_mode: host
    environment:
      TZ: 'Europe/Stockholm'
      WEBPASSWORD: 'Password'
      ServerIP: '192.168.1.10'
      DNS1: '9.9.9.9'
      DNS2: '149.112.112.112'
      DNSSEC: 'true'
    volumes:
      - './data/etc-pihole/:/etc/pihole/'
      - './data/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped